### ISSUE TITLE
Admin can chat with an agent directly

### ISSUE THREAD

**Issue by dinhnguyentrunghoa** [miaconsults/mia#114]

**Comment by dinhnguyentrunghoa** [comment]
@BettyGervasini  As the previous discussion, we will allow the admin chat with an agent directly in case: 
- This ticket takes a long time 
- Sending profile to the user
Thinking more, we should allow admin chat with the user directly, too. What do you think

**Comment by BettyGervasini** [comment]
@Hoa instead of letting admin to chat directly with end-user (which I believe this does not look good and it will be difficult to control), we should have a function where end-user can contact customer service (ie admin) to escalate and make his / her complains.
There must be remark or comments that end-user can put through to customer service or admin for their frustration or praise.
